/**
 * Markdown Reporter - generates analysis-report.md
 */

import {
  FindingsArtifact,
  RiskRegisterArtifact,
  Finding,
  RiskSeed,
  Severity,
} from "../types/artifacts.js";
import { writeFileSync } from "node:fs";
import path from "node:path";

/**
 * Get severity badge emoji
 */
function severityBadge(severity: Severity): string {
  switch (severity) {
    case "critical":
      return "**CRITICAL**";
    case "high":
      return "**HIGH**";
    case "medium":
      return "*MEDIUM*";
    case "low":
      return "LOW";
    default:
      return severity;
  }
}

/**
 * Count findings by severity
 */
function countBySeverity(findings: Finding[]): Record<Severity, number> {
  const counts: Record<Severity, number> = {
    critical: 0,
    high: 0,
    medium: 0,
    low: 0,
  };
  for (const finding of findings) {
    counts[finding.severity]++;
  }
  return counts;
}

/**
 * Generate analysis report markdown
 */
export function generateAnalysisReport(
  findings: FindingsArtifact,
  riskRegister: RiskRegisterArtifact,
  repoRoot: string
): string {
  const counts = countBySeverity(findings.findings);
  const totalFindings = findings.findings.length;
  const totalRisks = riskRegister.risks.length;
  const highRisks = riskRegister.risks.filter(
    (r) => r.severity === "high" || r.severity === "critical"
  );

  let md = `# code-to-gate Analysis Report

**Generated**: ${findings.generated_at}
**Run ID**: ${findings.run_id}
Repository: ${repoRoot}
**Tool**: code-to-gate v${findings.tool.version}

---

## Summary

| Metric | Count |
|--------|-------|
| Total Findings | ${totalFindings} |
| Critical | ${counts.critical} |
| High | ${counts.high} |
| Medium | ${counts.medium} |
| Low | ${counts.low} |
| Total Risks | ${totalRisks} |
| Unsupported Claims | ${findings.unsupported_claims.length} |

`;

  // Add high risks section if any
  if (highRisks.length > 0) {
    md += `## High-Priority Risks

| Risk ID | Title | Severity | Likelihood | Source Findings |
|---------|-------|----------|------------|-----------------|
`;
    for (const risk of highRisks) {
      const sourceFindings = risk.sourceFindingIds.join(", ");
      md += `| ${risk.id} | ${risk.title} | ${severityBadge(risk.severity)} | ${risk.likelihood} | ${sourceFindings} |\n`;
    }
    md += "\n";
  }

  // Add all findings table
  if (findings.findings.length > 0) {
    md += `## All Findings

| ID | Rule | Category | Severity | Title |
|----|------|----------|----------|-------|
`;
    for (const finding of findings.findings) {
      md += `| ${finding.id} | ${finding.ruleId} | ${finding.category} | ${severityBadge(finding.severity)} | ${finding.title} |\n`;
    }
    md += "\n";
  }

  // Add risk narratives
  if (riskRegister.risks.length > 0) {
    md += `## Risk Narratives

`;
    for (const risk of riskRegister.risks) {
      md += `### ${risk.id}: ${risk.title}

**Severity**: ${severityBadge(risk.severity)}
**Likelihood**: ${risk.likelihood}
**Confidence**: ${risk.confidence.toFixed(2)}

`;
      if (risk.narrative) {
        md += `${risk.narrative}\n\n`;
      }

      md += `**Impact**:
`;
      for (const impactItem of risk.impact) {
        md += `- ${impactItem}\n`;
      }
      md += "\n";

      md += `**Recommended Actions**:
`;
      for (const action of risk.recommendedActions) {
        md += `- ${action}\n`;
      }
      md += "\n---\n\n";
    }
  }

  // Add recommended actions summary
  md += `## Recommended Actions Summary

`;
  const allActions = riskRegister.risks.flatMap((r) => r.recommendedActions);
  const uniqueActions = [...new Set(allActions)];

  if (uniqueActions.length > 0) {
    md += `### Priority Order

`;
    // Sort by severity of source risk
    const sortedRisks = [...riskRegister.risks].sort((a, b) => {
      const severityOrder: Record<Severity, number> = {
        critical: 0,
        high: 1,
        medium: 2,
        low: 3,
      };
      return severityOrder[a.severity] - severityOrder[b.severity];
    });

    let priority = 1;
    for (const risk of sortedRisks) {
      for (const action of risk.recommendedActions) {
        md += `${priority}. **[${risk.severity.toUpperCase()}]** ${action}\n`;
        priority++;
      }
    }
    md += "\n";
  }

  // Add footer
  md += `---

*This report was generated by code-to-gate. Findings are based on static analysis of the repository.*

`;

  return md;
}

/**
 * Write analysis-report.md to output directory
 */
export function writeAnalysisReportMd(
  outDir: string,
  findings: FindingsArtifact,
  riskRegister: RiskRegisterArtifact,
  repoRoot: string
): string {
  const filePath = path.join(outDir, "analysis-report.md");
  const content = generateAnalysisReport(findings, riskRegister, repoRoot);
  writeFileSync(filePath, content, "utf8");
  return filePath;
}